import base64
import io
import zipfile

import requests
from fastapi.testclient import TestClient

from backend import main


client = TestClient(main.app)


class FakeResponse:
    def __init__(self, payload=None, *, text="", status_code=200, url="https://example.test"):
        self._payload = payload
        self.text = text
        self.status_code = status_code
        self.url = url

    def json(self):
        return self._payload

    def raise_for_status(self):
        if self.status_code >= 400:
            raise requests.HTTPError(f"HTTP {self.status_code}")


def refresh_fixture(monkeypatch):
    secret = "refresh-secret"
    repository = "BusiM5/ai-site-the-founder-s-architect-20260716045625-1dea5905"
    commit_sha = "a" * 40
    site_slug = "ai-site-the-founder-s-architect-67c07d57"
    live_url = f"https://{site_slug}.netlify.app"
    source_html = main.ensure_required_site_features(
        "<!doctype html><html><head><title>Founder</title></head><body><header class='hero'>"
        "<h1>The Founder's Architect</h1></header></body></html>"
    )
    readme = (
        "# The Founder's Architect\n\n"
        "Generated by AI Site Factory.\n\n"
        "- Canonical lead key: `67c07d5746c3a2db`\n"
        f"- HTML checksum: `{main.html_checksum(source_html)}`\n"
    )
    field_ids = {
        "campaignId": "1",
        "pipelineId": "2",
        "canonicalLeadKey": "3",
        "approvalId": "4",
        "businessName": "5",
        "liveUrl": "6",
        "deployRequested": "7",
        "leadStatus": "8",
        "contactChannel": "9",
    }
    values = {
        "1": "2a3622e1-73f2-5193-beed-f12db4c60f2f",
        "2": "2a3622e1-73f2-5193-beed-f12db4c60f2f",
        "3": "67c07d5746c3a2db",
        "4": "778b956e-b307-50f0-9e1f-c302205c7a68",
        "5": "The Founder's Architect",
        "6": live_url,
        "7": True,
        "8": "asf_cf_status_deployed",
        "9": "asf_cf_channel_phone",
    }
    ticket = {
        "id": 5808,
        "brand_id": 28776034680988,
        "ticket_form_id": 28911251022492,
        "external_id": "asf:2a3622e1-73f2-5193-beed-f12db4c60f2f:67c07d5746c3a2db:phone:intake",
        "status": "open",
        "tags": [
            "asf_managed",
            "asf_authoritative",
            "asf_deployed",
            "asf_stage_live",
            "asf_channel_phone",
            "asf_form_call_lead",
            "asf_deploy_phone_fired",
        ],
        "custom_fields": [{"id": int(key), "value": value} for key, value in values.items()],
    }
    contract = {
        "channel": "phone",
        "brandId": 28776034680988,
        "formId": 28911251022492,
        "fieldIds": field_ids,
    }
    monkeypatch.setenv("ZENDESK_WEBHOOK_SECRET", secret)
    monkeypatch.setenv("GITHUB_OWNER", "BusiM5")
    monkeypatch.setenv("GITHUB_TOKEN", "github-token")
    monkeypatch.setenv("NETLIFY_AUTH_TOKEN", "netlify-token")
    monkeypatch.setattr(main, "require_zendesk_ticket_contract", lambda channel, verify_live=False: contract)
    monkeypatch.setattr(
        main,
        "zendesk_api_request",
        lambda method, path: {"ticket": ticket},
    )
    return {
        "secret": secret,
        "repository": repository,
        "commitSha": commit_sha,
        "siteSlug": site_slug,
        "siteId": "opaque-site-id",
        "liveUrl": live_url,
        "sourceHtml": source_html,
        "readme": readme,
    }


def github_content(value):
    content = value.encode("utf-8")
    return {
        "type": "file",
        "encoding": "base64",
        "size": len(content),
        "content": base64.b64encode(content).decode("ascii"),
    }


def request_payload(data):
    return {
        "zendeskTicketId": 5808,
        "channel": "phone",
        "repository": data["repository"],
        "expectedCommitSha": data["commitSha"],
    }


def install_provider_fakes(monkeypatch, data, *, live_is_current):
    state = {"deployed": False, "posts": []}

    def fake_get(url, **kwargs):
        if url == f"https://api.github.com/repos/{data['repository']}":
            return FakeResponse(
                {
                    "full_name": data["repository"],
                    "owner": {"login": "BusiM5"},
                    "default_branch": "main",
                    "archived": False,
                    "disabled": False,
                },
                url=url,
            )
        if url == f"https://api.github.com/repos/{data['repository']}/commits/{data['commitSha']}":
            return FakeResponse({"sha": data["commitSha"]}, url=url)
        if url == f"https://api.github.com/repos/{data['repository']}/contents/index.html":
            return FakeResponse(github_content(data["sourceHtml"]), url=url)
        if url == f"https://api.github.com/repos/{data['repository']}/contents/README.md":
            return FakeResponse(github_content(data["readme"]), url=url)
        if url == f"https://api.netlify.com/api/v1/sites/{data['siteSlug']}.netlify.app":
            return FakeResponse(
                {
                    "id": data["siteId"],
                    "name": data["siteSlug"],
                    "ssl_url": data["liveUrl"],
                    "build_settings": {},
                },
                url=url,
            )
        if url.startswith(f"{data['liveUrl']}/?asf_refresh="):
            current = live_is_current or state["deployed"]
            return FakeResponse(
                text=data["sourceHtml"] if current else "<!doctype html><html><body>old</body></html>",
                url=data["liveUrl"],
            )
        raise AssertionError(f"Unexpected GET {url}")

    def fake_post(url, **kwargs):
        state["posts"].append((url, kwargs))
        assert url == f"https://api.netlify.com/api/v1/sites/{data['siteId']}/deploys"
        state["deployed"] = True
        return FakeResponse(
            {
                "id": "deploy-1",
                "site_id": data["siteId"],
                "state": "ready",
                "ssl_url": data["liveUrl"],
            },
            url=url,
        )

    monkeypatch.setattr(main.requests, "get", fake_get)
    monkeypatch.setattr(main.requests, "post", fake_post)
    return state


def test_refresh_rejects_bad_secret_before_provider_calls(monkeypatch):
    data = refresh_fixture(monkeypatch)
    monkeypatch.setattr(main.requests, "get", lambda *args, **kwargs: (_ for _ in ()).throw(AssertionError("GET called")))
    monkeypatch.setattr(main.requests, "post", lambda *args, **kwargs: (_ for _ in ()).throw(AssertionError("POST called")))

    response = client.post(
        "/api/admin/existing-generated-site/refresh",
        json=request_payload(data),
        headers={"x-ai-site-factory-secret": "wrong"},
    )

    assert response.status_code == 401


def test_refresh_is_idempotent_and_never_creates_a_site_or_repo(monkeypatch):
    data = refresh_fixture(monkeypatch)
    state = install_provider_fakes(monkeypatch, data, live_is_current=False)
    headers = {"x-ai-site-factory-secret": data["secret"]}

    first = client.post(
        "/api/admin/existing-generated-site/refresh",
        json=request_payload(data),
        headers=headers,
    )
    second = client.post(
        "/api/admin/existing-generated-site/refresh",
        json=request_payload(data),
        headers=headers,
    )

    assert first.status_code == 200, first.text
    assert first.json()["status"] == "REFRESHED_EXISTING_SITE"
    assert first.json()["siteCreated"] is False
    assert first.json()["repoCreated"] is False
    assert first.json()["aiGenerationCount"] == 0
    assert second.status_code == 200, second.text
    assert second.json()["status"] == "ALREADY_CURRENT"
    assert len(state["posts"]) == 1
    post_url, post_kwargs = state["posts"][0]
    assert post_url.endswith(f"/sites/{data['siteId']}/deploys")
    assert post_url != "https://api.netlify.com/api/v1/sites"
    assert post_kwargs["headers"]["Content-Type"] == "application/zip"
    with zipfile.ZipFile(io.BytesIO(post_kwargs["data"])) as archive:
        assert archive.read("index.html").decode("utf-8") == data["sourceHtml"]


def test_refresh_already_current_skips_netlify_post(monkeypatch):
    data = refresh_fixture(monkeypatch)
    state = install_provider_fakes(monkeypatch, data, live_is_current=True)

    response = client.post(
        "/api/admin/existing-generated-site/refresh",
        json=request_payload(data),
        headers={"x-ai-site-factory-secret": data["secret"]},
    )

    assert response.status_code == 200, response.text
    assert response.json()["status"] == "ALREADY_CURRENT"
    assert state["posts"] == []
